spring:
  application:
    name: tiny-ledger

  datasource:
    url: jdbc:h2:mem:ledger;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
